name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Display changes made
      run: |
        echo "Cambios realizados: $(date)"
        echo "Mensaje del último commit: $(git log -1 --pretty=%B)"
        echo "Autor del último commit: $(git log -1 --pretty=%an)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-web-app:latest
